version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    image: jiho314518/humax16
    expose:
      - "3000"
    ports:
      - "3000:3000"

#  redis:
#    build:
#      context: .
#      dockerfile: Dockerfile-redis
#    container_name: redisì• 
#    image: jiho314518/humax16_redis
#    expose:
#      - "6379"
#    ports:
#      - "6379:6379"